### ISSUE TITLE
Anchor parameters using Facets estimates

### ISSUE THREAD

**Issue by ck37** [alexanderrobitzsch/TAM#10]
Hello,

A related question: any advice or sample code for taking parameters estimated in Facets and then using them to anchor the parameters in TAM? In particular, I'm not sure how to convert the item difficulties and item step parameters in Facets into the delta parameters expected by TAM in the xsi argument (as shown at http://www.edmeasurementsurveys.com/TAM/Tutorials/5PartialCredit.htm).

In my case I have 10 items, each with 3-5 response options. So my parameter estimates from Facets look like this:

```
# We have 10 sets of item step parameters
Rating (or partial credit) scale = RS1,R,G,O
 0=,0,A
 1=,-.705287,A
 2=,-.5381367,A
 3=,.2757481,A
 4=,.9676757,A
 ; Rasch-Andrich Thresholds =0, -.705287, -.5381367, .2757481, .9676757
# Repeat 9 more times for the other items

# And the 10 item difficulties:
 1=1,-.9633994
 2=2,-.7767381
 3=3,-.4495207
 4=4,-.1540963
 5=5,-.4207196
 6=6,.3016304
 7=7,1.080987
 8=8,1.475
 9=9,-.7185087
 10=10,.6253652
```

My TAM code would then be something like:

```r
result = TAM::tam(data, xsi.fixed = tam_params, irtmodel = "PCM")
```

I'm hoping to get the ConQuest equivalent of a PCM model with the formula item + item*step.

I would be glad to provide any other details that would be helpful.

Many thanks,
Chris

**Comment by alexanderrobitzsch** [comment]
Maybe you can use the argument ``irtmodel='PCM2'`` which should provide the requested parameterization. You could also have a look at ``sirt::pcm.conversion``, see [https://alexanderrobitzsch.github.io/sirt/reference/pcm.conversion.html](https://alexanderrobitzsch.github.io/sirt/reference/pcm.conversion.html)

**Comment by ck37** [comment]
Thank you for the pointer, it is greatly appreciated.

I have been trying to get this conversion working but something seems to be off.

Here is my conversion code that is attempting to implement the formula from pcm.conversion. One question though: does the k index start at 0 or 1? And am I correct in believing that delta_i refers to the item difficulty parameter from ConQuest/Facets, and tau_ik refers to the item step parameter?

```r
param_steps = params[params$type == "item_step", ]
param_steps$b = NA

# Loop over each item step from Facets and convert to TAM's b parameter. 
for (step_i in seq(nrow(param_steps))) {
  step = param_steps[step_i, ]
  
  # Extract the item difficulty.
  item_difficulty = params[params$type == "item" & params$item_name == step$item_name, "value"]
  
  # Extract any lower steps for this item.
  lower_steps = subset(param_steps, param_steps$item_name == step$item_name &
                         param_steps$step_value < step$step_value)
  
  # See formula at https://alexanderrobitzsch.github.io/sirt/reference/pcm.conversion.html
  # b_ik = k * delta_i + \sum_{v = 1}^k tau_iv
  # Unclear which version is desired --
  #b = (step$step_value + 1) * item_difficulty + sum(lower_steps$value) + step$value
  b = step$step_value * item_difficulty + sum(lower_steps$value) + step$value
  param_steps$b[step_i] = b
}

# We only need the non-zero steps (i.e. omit the first category for each item).
param_steps = param_steps[param_steps$b != 0, ]
```

Then after I run the scaling and look compare the item difficulties using pcm.conversion, I find that the difficulties are highly correlated but are scaled differently :/. So it appears that I am not converting the TAM parameters to Facets correctly.

```r
result = TAM::tam(data[, 3:12],
                  xsi.fixed = as.matrix(tam_params[, c("i", "b")]),
                  irtmodel = "PCM")

######
# If we take the result of the anchored IRT estimation and convert it back to
# Facets/ConQuest parameterization, we can check if our initial conversion worked.
b = result$item[, c("AXsi_.Cat1","AXsi_.Cat2","AXsi_.Cat3", "AXsi_.Cat4")]

# Convert TAM parameters back to Facets-style parameter.
print({ conv = sirt::pcm.conversion(b) } )
print(comparison <- cbind.data.frame("tam_delta" = conv$delta,
                               "facets" = params[params$type == "item", c("value")]))
# Item difficulty parameters are highly correlated! 0.98 - 0.99
# The scale is a different though.
cor(comparison$tam_delta, params[params$type == "item", "value"])
qplot(comparison$tam_delta, comparison$facets) + theme_minimal()
```

Comparison of the item difficulty parameters:
```
               tam_delta     facets
sentiment     -3.1375950 -0.9633994
respect       -2.5770415 -0.7767381
insult        -1.7851986 -0.4495207
humiliate     -1.2626005 -0.1540963
status        -2.0884787 -0.4207196
dehumanize    -0.0650817  0.3016304
violence_phys  2.4126986  1.0809870
genocide       3.6860765  1.4750000
attack_defend -3.1489974 -0.7185087
hatespeech     1.6935888  0.6253652
```

This also shows up in the score distribution being overly dispersed from TAM.

Any leads or tips would be greatly appreciated, as I am still a bit new to the theory of IRT.

**Comment by alexanderrobitzsch** [comment]
It is hard to tell without seeing data and code (maybe send it to me via email). The Facets software uses a different estimation algorithm, so comparisons of ``TAM`` should be rather made with ConQuest.

**Comment by ck37** [comment]
Ok I will send you an email with the data and more background context - appreciate it

**Comment by jinchanghsieh** [comment]
Dear all. Following the above question, how can I fix "step parameters" using xsi.fixed argument? I know how to fix overall difficulty parameters but don't know how to fix step parameter. thanks for your response.

**Comment by alexanderrobitzsch** [comment]
A step parameter is just one element in the ``xsi`` vector. Hence, it can be be fixed in the same way as item parameters.

**Comment by jinchanghsieh** [comment]
Thanks for your response. Really appreciate. The other question is what is the default estimation model while doing multidimensions. When I use the following codes to estimate 4-dims model, different specifications of irtmodel= may have different results with the same partial credit data(scoring with 0123). The specificaion include no specification(default)(showed as follows), irtmodel=PCM, irtmodel=PCM2, irtmodel=GPCM.

mod4_1a <- TAM::tam.mml(resp=db_E[12:41], Q=Q, constraint="items",pweights = db_E$Weight_Eng_SCHcla, pid= db_E$stuid, control=list(snodes=2000,QMC=FALSE))

**Comment by jinchanghsieh** [comment]
Beside the quesiton(default irtmodel with multidimensional partial credit data) above, even the same model with the same data but calibrated twice, the results between the two times are also slightly different. I don't why? Is it something about the code "snodes=2000,QMC=FALSE" (schocastic integration)? 
Really thanks for your responses.

**Comment by alexanderrobitzsch** [comment]
When using stochastic integration, a grid is randomly drawn. Either you use ``QMC=TRUE`` or you fix the seed, e.g., using ``set.seed(123)``.

**Comment by alexanderrobitzsch** [comment]
## "  irtmodel=PCM, irtmodel=PCM2, irtmodel=GPCM. "
PCM and PCM2 provide different parameterizations, but should result in the same likelihood. Of course, the GPCM also estimates slope parameters.
