### ISSUE TITLE
Error in plot.tam: theta0 not found

### ISSUE THREAD

**Issue by sda030** [alexanderrobitzsch/TAM#12]
After the update to TAM 3.4-26, there is an error in
`plot(mod_2PL, items = 1, type = "expected", wle=mod_2PL_abilities[["theta"]])
Error in plot.tam.mml(mod_1PL, items = 1, type = "expected", : 
  object 'theta0' not found`
which "makes sense" when investigating the code, as line 423 assumes that theta0 exists, even though it only comes into existence when `type="items"`. You have initiated a `theta2 <- NULL`, has there been any mixup between theta0 and theta2? (I haven't scrutinized your code in detail)

**Comment by alexanderrobitzsch** [comment]
Thank you for reporting. When working on the output of ``plot.tam()`` in the last version update, ``theta0`` gots lost somewhere. I will upload a bugfix on Github in the next hour.
