### ISSUE TITLE
Number of parameters identical with 2PL and GPCM (>2 categories)

### ISSUE THREAD

**Issue by uhkeller** [alexanderrobitzsch/TAM#17]
Hello,

sorry if I'm missing something obvious here, but if I run the 2PL and GPCM examples from the `tam.mml` help page, the number of parameters in the `summary()` output is the same for both models, 9 threshold parameters (ok) and 9 slope parameters. Shouldn't it just be 3 slope parameters for the GPCM?

```r
data(data.gpcm, package="TAM")
mod6_1 <- TAM::tam.mml.2pl( resp=data.gpcm, irtmodel="2PL", control=list(maxiter=200) )
summary(mod6_1)

##     Item threshold parameters = 9 
##     Item slope parameters = 9 

mod6_2 <- TAM::tam.mml.2pl( resp=data.gpcm, irtmodel="GPCM", control=list(maxiter=200))
summary(mod6_2)

##     Item threshold parameters = 9 
##     Item slope parameters = 9 
```

I'm using TAM 3.5-19.

**Comment by alexanderrobitzsch** [comment]
Thanks for reporting. This was indeed a bug. I corrected it in the dev version ``TAM 3.6-41``, which will be on Github in a few minutes,
