### ISSUE TITLE
irtmodel = "RSM" is not working when constraint = "items"

### ISSUE THREAD

**Issue by xiaozhanzi** [alexanderrobitzsch/TAM#19]
Hi,
Thank you for your package. It's a great package for doing the Rasch analysis which benefits me a lot.
Recently, when I conducted the multidimensional Rasch analysis with the following syntax:
            TAM::tam.mml(resp = df, irtmodel = "RSM", constraint = "items", Q = Q2, control = list(maxiter = 200, snodes = 2000))
Instead of using the default setting, here I changed the constraint to "items".  Everything went smoothly, but when I checked the result, it reported the PCM2 model results, not the "RSM" results.  It's there something wrong with my syntax?

**Comment by alexanderrobitzsch** [comment]
I suppose that ``constraint="items"`` is not implemented for ``irtmodel="RSM"``. Maybe I do not see why one should ever employ the ``items`` constraint.

**Comment by xiaozhanzi** [comment]
Many thanks for your reply. I want to get a similar report like that in
ConQuest.  When doing the multidimensional Rasch analysis with
 "item+step" , ConQuest constrains the last item of each dimension and
reports a general step statistic. I wonder if TAM can do a similar analysis
with that in ConQuest? Appreciate your kind suggestion and help.
