### ISSUE TITLE
tam.fa calls GPArotation::oblimin() with unused argument (L = B.stand)

### ISSUE THREAD

**Issue by Stegmannk** [alexanderrobitzsch/TAM#22]
Hi!

The current version of tam.fa() calls GPArotation::oblimin(L = B.stand). GPArotation::oblimin, however, hasn't an argument called L. Instead of L, A might might be the correct argument. A fix to this problem would be highly appreciated!

Thank you very much

Best regards,
Karsten Stegmann

R 3.4.1 (MAC OS, ARM)
GPArotation version 2023.3-1
TAM version 4.1-4

**Comment by bernaards** [comment]
Yeah, with version 2023.3-1 includes this change. Removal of "L=" works, or change to "A="
