### ISSUE TITLE
Error in GPArotation::oblimin(L = B.stand) unused argument (L = B.stand)

### ISSUE THREAD

**Issue by zhaokoh** [alexanderrobitzsch/TAM#23]
Hi,

Thank you so much for creating and maintaining this R package. I encountered the following error while running ``tam.fa` today.

When I ran:

```tam.fa(responses_df, irtmodel = "efa", nfactor = 9, verbose = FALSE)```

After a while, it failed and displayed the following error message:

```
Error in GPArotation::oblimin(L = B.stand) : 
  unused argument (L = B.stand)
```

The package versions that I am using are:

```
> packageVersion("TAM")
[1] ‘4.1.4’
> packageVersion("GPArotation")
[1] ‘2023.8.1’
```

This may not be a bug but could be version conflicts between packages.

**Comment by alexanderrobitzsch** [comment]
Please see [https://github.com/alexanderrobitzsch/TAM/issues/22](https://github.com/alexanderrobitzsch/TAM/issues/22) and use the recent Github TAM dev version.
