### ISSUE TITLE
Partial Credit Items with Max Scores of 1.5 out of bounds error

### ISSUE THREAD

**Issue by Draic** [alexanderrobitzsch/TAM#3]
I have a dataset with both simple multiple choice and complex multiple choice questions. Complex questions give 0.5 points per partial answer (similar to example case #19 in the documentation). TAM works with the partial credit items that have a max of 2 point, 2.5 points etc. but it seems to break if the max score of a question is 1.5. If there is a column with a max of 1.5 no matter what I try to adjust, I will get a "Error in `[<-`(`*tmp*`, ii, kk:(Kitem[ii] - 1), vv, value = -1) : 
  subscript out of bounds" message.
As I said, there seems to be no problem with questions that give out a max of 2.5 points. My error is specific to a max of 1.5 for some reason

I am trying to replicate the results from a previous ConQuest work, but I cannot find a way to make TAM behave with my dataset. This is the model as defined in ConQuest: "estimate ! method=gauss, nodes = 15; iterations = 1000; convergence = 0.0001;;". 

I am not sure if this is a bug, a limitation of the package or just my stupidity. In case it is the latter, some help would be appreciated. Thanks

[exampledata.zip](https://github.com/alexanderrobitzsch/TAM/files/2543255/exampledata.zip)
I have a attached .RData with a subset of my questionnaire. The problematic column is the second one named "icg12107s_c". This will result the subscript out of bounds message.

**Comment by alexanderrobitzsch** [comment]
According to the manual, `resp` must be a data frame with only integer scores. If requested, scorings should be included in the `B` design matrix.
