### ISSUE TITLE
Would like to use tam.modelfit with tam.jml object

### ISSUE THREAD

**Issue by thoughtafter** [alexanderrobitzsch/TAM#4]
We would like to use modelfit with ``tam.jml`` output. Is this currently possible? If so, how? If not can this be added?

````
mod<-tam.jml(D1)
tam.modelfit(mod)
**** Calculate Residuals 
Error in tam_rcpp_modelfit_residuals(rprobs = as.vector(rprobs), resp = resp,  : 
  Not compatible with requested type: [type=NULL; target=double].
IRT.modelfit(mod)
Error in UseMethod("IRT.modelfit") : 
  no applicable method for 'IRT.modelfit' applied to an object of class "tam.jml"
````

**Comment by alexanderrobitzsch** [comment]
The ``tam.modelfit`` function evaluates the fit of the posterior distribution of $\theta$ which is not available for JML estimation because ability parameters are treated as fixed effects. If you would like to have access to these statistics, I would switch to MML estimation.
